### ISSUE TITLE
Update candidate deduplication based on decision at IETF 95: choose highest priority

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/trickle#6]
At IETF 95, we decided to update duplicate (prflx/srflx) candidates to the highest priority (neither last wins nor highest wins).   We need to update the draft text.

Minutes:

https://www.ietf.org/proceedings/95/minutes/minutes-95-ice

**Comment by taylor-b** [comment]
Copy of message I sent to the mailing list about this issue:

I see a potential issue with this, specifically regarding peer reflexive candidates.

It's possible for a remote peer reflexive candidate to be created simply because a binding request was received before the candidate was signaled. Then, according to this rule, the peer reflexive candidate would not be replaced by the server reflexive candidate when it's signaled, because the peer reflexive candidate is guaranteed to have a higher priority.

As a result, the endpoints will prioritize the same candidate pair differently, because one endpoint sees the candidate as peer reflexive while the other sees it as something else. This means the endpoints could have different ideas of which candidate pair is the highest priority, which could result in sub-optimal selection of a candidate pair, or asymmetric selection if the controlling agent is an RFC 5245 endpoint that uses aggressive nomination.

So, I suggest a minor modification to the rule: peer reflexive candidates are always replaced by other types of candidates, regardless of priority.

**Comment by pthatcherg** [comment]
I agree with Taylor that we have a rule of "signalled wins (over prflx), then hight priority wins".
